-- ============================================================
-- Supabase/PostgreSQL Schema for DataQuest (Normalization Quest Lab)
-- Converted from MySQL original. Run this in Supabase SQL Editor.
-- ============================================================

-- Drop existing tables (reverse order for FK dependencies)
DROP TABLE IF EXISTS logros_usuario CASCADE;
DROP TABLE IF EXISTS dominios_aprendizaje CASCADE;
DROP TABLE IF EXISTS logs_sistema CASCADE;
DROP TABLE IF EXISTS participaciones_reto CASCADE;
DROP TABLE IF EXISTS retos_semanales CASCADE;
DROP TABLE IF EXISTS intentos_puzzle CASCADE;
DROP TABLE IF EXISTS puzzles CASCADE;
DROP TABLE IF EXISTS validaciones CASCADE;
DROP TABLE IF EXISTS esquemas CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS blocked_terms CASCADE;

-- ============================================================
-- Table: blocked_terms (Palabras/Nombres Prohibidos)
-- ============================================================
CREATE TABLE blocked_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL DEFAULT 'general',
    severity TEXT NOT NULL DEFAULT 'medium',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE INDEX idx_blocked_terms_category ON blocked_terms(category);
CREATE INDEX idx_blocked_terms_is_active ON blocked_terms(is_active);

COMMENT ON TABLE blocked_terms IS 'Términos y nombres prohibidos para validación';

-- Initial blocked terms data
INSERT INTO blocked_terms (term, category, severity, description) VALUES
-- Historical inappropriate names
('hitler', 'historical_inappropriate', 'high', 'Nombre históricamente inapropiado'),
('nazi', 'hate_reference', 'high', 'Referencia a odio'),
('ss', 'hate_reference', 'high', 'Referencia histórica inapropiada'),
('gestapo', 'hate_reference', 'high', 'Referencia histórica inapropiada'),
-- Reserved names
('admin', 'reserved_name', 'medium', 'Nombre reservado del sistema'),
('administrator', 'reserved_name', 'medium', 'Nombre reservado del sistema'),
('root', 'reserved_name', 'medium', 'Nombre reservado del sistema'),
('superuser', 'reserved_name', 'medium', 'Nombre reservado del sistema'),
('mod', 'reserved_name', 'medium', 'Nombre reservado del sistema'),
('moderator', 'reserved_name', 'medium', 'Nombre reservado del sistema'),
-- Invalid names
('null', 'invalid_name', 'medium', 'Palabra reservada de programación'),
('undefined', 'invalid_name', 'medium', 'Palabra reservada de programación'),
('test', 'invalid_name', 'low', 'Nombre de prueba no permitido'),
('testing', 'invalid_name', 'low', 'Nombre de prueba no permitido'),
('prueba', 'invalid_name', 'low', 'Nombre de prueba no permitido'),
('demo', 'invalid_name', 'low', 'Nombre de prueba no permitido'),
-- Offensive terms
('puto', 'offensive', 'high', 'Término ofensivo'),
('puta', 'offensive', 'high', 'Término ofensivo'),
('pendejo', 'offensive', 'high', 'Término ofensivo'),
('pendeja', 'offensive', 'high', 'Término ofensivo'),
('mierda', 'offensive', 'high', 'Término ofensivo'),
('culero', 'offensive', 'high', 'Término ofensivo'),
('culera', 'offensive', 'high', 'Término ofensivo'),
('verga', 'offensive', 'high', 'Término ofensivo'),
('cojones', 'offensive', 'high', 'Término ofensivo'),
('carajo', 'offensive', 'high', 'Término ofensivo'),
('cabron', 'offensive', 'high', 'Término ofensivo'),
('cabrona', 'offensive', 'high', 'Término ofensivo'),
('estupido', 'offensive', 'medium', 'Término ofensivo'),
('estupida', 'offensive', 'medium', 'Término ofensivo'),
('idiota', 'offensive', 'medium', 'Término ofensivo'),
('imbecil', 'offensive', 'medium', 'Término ofensivo'),
('tonto', 'offensive', 'low', 'Término ofensivo'),
('tonta', 'offensive', 'low', 'Término ofensivo'),
-- Violence
('matar', 'violence', 'high', 'Término violento'),
('asesino', 'violence', 'high', 'Término violento'),
('bomba', 'violence', 'high', 'Término violento'),
('terrorista', 'violence', 'high', 'Término violento'),
-- Incoherent / spam patterns
('aaaa', 'incoherent', 'low', 'Caracteres repetidos sin sentido'),
('bbbb', 'incoherent', 'low', 'Caracteres repetidos sin sentido'),
('1234', 'incoherent', 'low', 'Solo números'),
('asdf', 'incoherent', 'low', 'Teclado sin sentido'),
('qwerty', 'incoherent', 'low', 'Teclado sin sentido'),
('zxcv', 'incoherent', 'low', 'Teclado sin sentido'),
-- Sexual explicit
('porno', 'sexual_explicit', 'high', 'Término sexual explícito'),
('xxx', 'sexual_explicit', 'high', 'Término sexual explícito'),
('sexo', 'sexual_explicit', 'high', 'Término sexual explícito')
ON CONFLICT (term) DO NOTHING;

-- ============================================================
-- Table: users
-- ============================================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo TEXT NOT NULL UNIQUE,
    apodo TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'usuario',
    xp INTEGER NOT NULL DEFAULT 0,
    rango TEXT NOT NULL DEFAULT 'Aprendiz',
    medallas TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_correo ON users(correo);
CREATE INDEX idx_users_apodo ON users(apodo);

COMMENT ON COLUMN users.role IS 'usuario or administrador';
COMMENT ON COLUMN users.medallas IS 'JSON array of medal strings';

-- ============================================================
-- Table: esquemas
-- ============================================================
CREATE TABLE esquemas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    nombre TEXT NOT NULL,
    estructura_json JSONB NOT NULL,
    dependencias_json JSONB,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_esquemas_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_esquemas_user ON esquemas(user_id);

-- ============================================================
-- Table: validaciones
-- ============================================================
CREATE TABLE validaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    esquema_id BIGINT NOT NULL,
    nivel_normalizacion TEXT NOT NULL,
    violaciones_json JSONB,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_validaciones_esquema FOREIGN KEY (esquema_id) REFERENCES esquemas(id) ON DELETE CASCADE
);

CREATE INDEX idx_validaciones_esquema ON validaciones(esquema_id);

-- ============================================================
-- Table: puzzles
-- ============================================================
CREATE TABLE puzzles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enunciado TEXT NOT NULL,
    tablas_inicial JSONB NOT NULL,
    df_inicial JSONB NOT NULL,
    solucion_esperada JSONB NOT NULL,
    nivel_dificultad INTEGER DEFAULT 1,
    activo BOOLEAN DEFAULT TRUE
);

-- ============================================================
-- Table: intentos_puzzle
-- ============================================================
CREATE TABLE intentos_puzzle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    puzzle_id BIGINT NOT NULL,
    puntuacion INTEGER NOT NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_intentos_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_intentos_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(id) ON DELETE CASCADE
);

CREATE INDEX idx_intentos_user ON intentos_puzzle(user_id);
CREATE INDEX idx_intentos_puzzle_id ON intentos_puzzle(puzzle_id);

-- ============================================================
-- Table: retos_semanales
-- ============================================================
CREATE TABLE retos_semanales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT NOT NULL,
    tablas JSONB NOT NULL,
    df JSONB NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    CONSTRAINT chk_fecha_fin CHECK (fecha_fin >= fecha_inicio)
);

-- ============================================================
-- Table: participaciones_reto
-- ============================================================
CREATE TABLE participaciones_reto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    reto_id BIGINT NOT NULL,
    puntuacion INTEGER NOT NULL,
    tiempo_segundos INTEGER NOT NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_participaciones_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_participaciones_reto FOREIGN KEY (reto_id) REFERENCES retos_semanales(id) ON DELETE CASCADE
);

CREATE INDEX idx_participaciones_user ON participaciones_reto(user_id);
CREATE INDEX idx_participaciones_reto_id ON participaciones_reto(reto_id);

-- ============================================================
-- Table: logs_sistema
-- ============================================================
CREATE TABLE logs_sistema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    user_id BIGINT,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_logs_user ON logs_sistema(user_id);
CREATE INDEX idx_logs_fecha ON logs_sistema(fecha);

-- ============================================================
-- Table: dominios_aprendizaje
-- ============================================================
CREATE TABLE dominios_aprendizaje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    concepto TEXT NOT NULL,
    porcentaje INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_dominios_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_concepto UNIQUE (user_id, concepto)
);

-- ============================================================
-- Table: logros_usuario
-- ============================================================
CREATE TABLE logros_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    medalla_nombre TEXT NOT NULL,
    desbloqueado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_logros_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_medalla UNIQUE (user_id, medalla_nombre)
);

-- ============================================================
-- Row Level Security for blocked_terms
-- ============================================================
ALTER TABLE blocked_terms ENABLE ROW LEVEL SECURITY;

-- Allow public read access only to active terms (for frontend validation if needed)
CREATE POLICY "Allow read active blocked terms"
ON blocked_terms
FOR SELECT
USING (is_active = true);

-- Replace the "Allow all for authenticated users" policy with admin-only
DROP POLICY IF EXISTS "Allow all for authenticated users" ON blocked_terms;

CREATE POLICY "Admin manage blocked_terms"
ON blocked_terms
FOR ALL
USING (
  auth.role() = 'authenticated'
  AND EXISTS (
    SELECT 1 FROM users
    WHERE users.id = auth.uid()
    AND users.role = 'administrador'
  )
)
WITH CHECK (
  auth.role() = 'authenticated'
  AND EXISTS (
    SELECT 1 FROM users
    WHERE users.id = auth.uid()
    AND users.role = 'administrador'
  )
);
